version: "3.8"

services:
  app1:
    build:
      context: ./SmolLM2Server
    ports:
      - "8001:8001"
    networks:
      - app-network
    environment:
      - MODEL_PATH=/path/to/your/model  # Optional: Adjust if needed

  app2:
    build:
      context: ./TextGenerator
    ports:
      - "8000:8000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
