name: Run CNN Model Tests

on:
  push:
    branches:
      - main  # Ensure you're pushing to the branch specified here
    paths:
      - 'TunningCNN/**'
  pull_request:
    branches:
      - main
    paths:
      - 'TunningCNN/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r TunningCNN/requirements.txt --no-deps

    - name: Run tests
      run: pytest TunningCNN/test_cnn_model.py
